### PR TITLE
Use project root instead of server root.

### PR DESCRIPTION
**Pull request by wadells**
If the docs are not hosted at the server root (e.g. https://goteleport.com/docs/) then we don't want to link to resources above our level.  In this particular case, `/` was linking to the homepage (https://goteleport.com/) instead of the latest docs (https://goteleport.com/docs/).

### CODE REVIEW

**Comment by wadells** [comment]
+ @ulysseskan as you recommended the wording updates in 96af0cd.

**Review by ulysseskan — COMMENTED** [review]
Looks good to me.

**Comment by iAdramelk** [comment]
@wadells thanks for finding this bug. But `"{root}"` will not work in this case. We need to directly set it to `"/docs/"`. Can you please change it?

**Comment by wadells** [comment]
> @wadells thanks for finding this bug. But `"{root}"` will not work in this case. We need to directly set it to `"/docs/"`. Can you please change it?

Won't docs break the previews that aren't behind the nginx reverse proxy?  Admittedly, those aren't nearly as important.

**Comment by iAdramelk** [comment]
@wadells NVM. It's better to fix broken production links asap, so I fixed it myself. Will merge it if staging deploy will finish without problems.

Thanks again.

**Comment by iAdramelk** [comment]
> Won't docs break the previews that aren't behind the nginx reverse proxy? Admittedly, those aren't nearly as important.

@wadells it's ok. We didn't redirect subfolder to the Vercel. Vercel also have `/docs/` folder. It's done to make future porting of the other pages easier

**Comment by iAdramelk** [comment]
It works https://teleport-docs-next-git-walt-latest-link-fix-gravitational.vercel.app/docs/ , merging.

**Comment by klizhentas** [comment]
Screen Shot 2021-04-02 at 2 06 38 PM
Screen Shot 2021-04-02 at 2 06 44 PM

@iAdramelk @wadells needs a couple of spaces after `:` and after `latest` see above

**Pull request merged**
