### PR TITLE
Add Troy Hunt Gated page

### PR DESCRIPTION
**Pull request by deliaconstantino**
- adds gated page for Troy Hunt webinar
- preview [here](https://teleport-docs-next-git-delia-troy-hunt-gated-page-gravitational.vercel.app/resources/videos/troy-hunt-lessons-from-billions-breached-records/)

### `<BookBlock />` updates:
Most instances of `<BookBlock />` were rendering text in `div` tags as shown here:
Screen Shot 2022-04-29 at 1 28 44 PM
- Updated these to `p` tags and updated styling as needed.
- preview an example at [/resources/white-papers/security-best-practices-for-pam/](https://teleport-docs-next-git-delia-troy-hunt-gated-page-gravitational.vercel.app/resources/white-papers/security-best-practices-for-pam/)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202168060587461

### CODE REVIEW

**Comment by sandylcruz** [comment]
If you want to make the original [Troy hunt webinar page](https://goteleport.com/resources/videos/troy-hunt-on-demand-lessons-from-billions-breached-records/) page to be gated by the [new page you added](https://github.com/gravitational/next/pull/1104/files#diff-02bfc1c6bab8f2df6f67454514c6c7178aacb08b4678812690139db121decb69), you need to change the original page's description to the following so it's not visible from the resources index page: ``` description: On demand```

**Review by jeffgaynor — COMMENTED** [review]
Something I'd like to see us all do whenever we commit images... compress. Try [ImageOptim](https://imageoptim.com/mac). 

image

**Comment by deliaconstantino** [comment]
@Sandy thanks for pointing this out. Updated the description to "On demand".

**Comment by deliaconstantino** [comment]
@jeffgaynor optimized the image. Thanks for sharing this resource.

**Review by sandylcruz — APPROVED** [review]

**Pull request merged**
