### PR TITLE
Update current ESA and move previous ESA to a new page

### PR DESCRIPTION
**Pull request by twakes**
Preview [new ESA](https://next-git-twakes-update-esa-gravitational.vercel.app/legal/esa/)
Preview [ESA Prior to 6-01](https://next-git-twakes-update-esa-gravitational.vercel.app/legal/esa-prior-06012022/)

Updating the ESA and moving this to a different page for existing Sales Orders.

### CODE REVIEW

**Comment by C-STYR** [comment]
@twakes when you're doing making changes I'll push a commit with the updated redirect (just @ me here or on slack @cole)

**Comment by twakes** [comment]
Hi @C-STYR ,

Looks like some of the items are being treated as <li> and some as <p>. Can we just make them all <p>? If it's not an easy fix, it's not a big deal. The indenting just looks strange.

**Comment by twakes** [comment]
@reedloden I was being lazy. I can make it look pretty.

**Comment by twakes** [comment]
Ok @reedloden added formatting. 

@C-STYR I think this is good to deploy when you are ready.

**Review by C-STYR — APPROVED** [review]

**Pull request merged**
