### PR TITLE
Small Readme Spelling Edits

### PR DESCRIPTION
**Pull request by irishgordo**
- just a few small spelling edits for documentation

Resolves: patch/sml-rdme-spell-edits

### CODE REVIEW

**Comment by irishgordo** [comment]
Hey there again,

Just was cruising through the README and saw a few spelling errors in the doc to possibly clean up a tad :).
Again, ya'll are doing some rad stuff!  Really digging it all!

**Comment by irishgordo** [comment]
It seems with "Vercel" I'm not able to see why the "Deployment has failed" error occurred. (404 Page)
I'm willing to fix whatever is needed to ensure safety, security, deployment success, etc. happens with the patch.
Is there anyway I could possibly get more details from the failure message?

**Comment by iAdramelk** [comment]
Thank you very much for your input! Merged.

**Comment by irishgordo** [comment]
Y'all are doing stellar stuff, glad I could help @iAdramelk !

**Pull request merged**
