### PR TITLE
Fix #228: Broken asset links

### LINKED ISSUE #228: Broken Images and Links in Docs
Our site score for SEO (search engine optimization) has decreased due to the following errors in docs. We need to fix these errors in order to get the score up. Let me know if you have any questions. 

### Pages with broken images
- https://goteleport.com/docs/enterprise/sso/ssh-one-login/  image: https://goteleport.com/img/sso/onelogin/teleport.png
- https://goteleport.com/docs/enterprise/sso/ssh-one-login/ image: https://goteleport.com/img/sso/onelogin/teleportlogo@2x.png
- https://goteleport.com/docs/enterprise/workflow/ssh-approval-mattermost/ image: https://goteleport.com/img/enterprise/plugins/teleport_bot@2x.png
- https://goteleport.com/docs/enterprise/workflow/ssh-approval-slack/ image: https://goteleport.com/img/enterprise/plugins/teleport_bot@2x.png

### Pages with Titles that are too long (70 characters is the max) 
- https://goteleport.com/docs/architecture/authentication/ change to: Teleport Authentication, SSH & Kubernetes certificates | Teleport Docs
- https://goteleport.com/docs/features/ssh-pam/ change to: Configuring Teleport SSH with PAM | Teleport Docs

### PR DESCRIPTION
**Pull request by iAdramelk**
`remark-links` should not modify local asset links.

### CODE REVIEW

**Comment by iAdramelk** [comment]
@klizhentas can you please deploy this PR to staging and run SemRush on it to make sure all links are fixed and no new links are broken. If yes, please merge it.

**Comment by klizhentas** [comment]
Screen Shot 2021-05-12 at 1 24 33 PM
 
@iAdramelk lots of errors on this branch

**Comment by iAdramelk** [comment]
@klizhentas my bad, broke links with hashes. Should work now.

**Review by klizhentas — APPROVED** [review]
All links have been fixed, you are good to go.

**Pull request merged**
